config/routes.rb
Rails.application.routes.draw do
	root 'courses#index'
	post 'courses', to: 'courses#create', as: 'courses'
	get 'courses/new', to: 'courses#new', as: 'new_course'
	get 'courses/:id/edit', to: 'courses#edit', as: 'edit_course'
	patch 'courses/:id', to: 'courses#update'
	get 'courses/:id', to: 'courses#show', as: 'course'
	resources :students, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	validates :code, presence: true, uniqueness: true, length: { minimum: 3, maximum: 12 }
	validates :name, presence: true, length: { minimum: 10, maximum: 60 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	has_many :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 253 }, format: { with: VALID_EMAIL_REGEX }
	validates :name, presence: true, length: { minimum: 3, maximum: 100 }
	has_secure_password
	has_many :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def custom_paginate_renderer
	  # Return nice pagination for materialize
	  Class.new(WillPaginate::ActionView::LinkRenderer) do
		  def container_attributes
		    {class: "pagination"}
		  end

		  def page_number(page)
		    if page == current_page
		      "<li class=\"blue lighten-2 active\">"+link(page, page, rel: rel_value(page))+"</li>"
		    else
		      "<li class=\"waves-effect\">"+link(page, page, rel: rel_value(page))+"</li>"
		    end
		  end

		  def previous_page
		    num = @collection.current_page > 1 && @collection.current_page - 1
		    previous_or_next_page(num, "<i class=\"small material-icons\">arrow_back</i>")
		  end

		  def next_page
		    num = @collection.current_page < total_pages && @collection.current_page + 1
		    previous_or_next_page(num, "<i class=\"small material-icons\">arrow_forward</i>")
		  end

		  def previous_or_next_page(page, text)
		    if page
		      "<li class=\"waves-effect\">"+link(text, page)+"</li>"
		    else
		      "<li class=\"disabled\">"+link(text, "#!")+"</li>"
		    end
		  end
	  end
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.paginate(:page => params[:page], :per_page => 4)
		@custom_paginate_renderer = custom_paginate_renderer
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)
		if @course.save
			flash[:success] = "Successfully created course: #{@course.name}"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def show
		@course = Course.find(params[:id])
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])
		if (@course.update(course_params))
			flash[:success] = "Successfully updated course: #{@course.name}"
			redirect_to course_path(@course)
		else
			render 'edit'
		end
	end

	private
		def course_params
			params.require(:course).permit(:code, :name, :description)
		end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)
		if @student.save
			flash[:success] = "Welcome to My University, #{@student.name}"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def index
		@students = Student.paginate(:page => params[:page], :per_page => 6)
		@custom_paginate_renderer = custom_paginate_renderer
	end

	def update
	end

	def show
	end

	private
		def student_params
			params.require(:student).permit(:name, :email, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<% if @course.errors.any? %>
	<div class="row">
		<div class="col s12 m12 l10">
			<div class="card-panel orange error-list">
				<h5 class="card-title"><%= pluralize(@course.errors.count, "error") %> occurred while trying to <%= @course.new_record? ? "create" : "update" %>:</h5>
				<ul>
					<% @course.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
<% end %>

<div class="row new-entity">
	<div class="col s12 m12 l10">
		<div class="card-panel">
			<div class="row">
				<%= form_for(@course) do |f| %>
					<h4 class="card-title new-entity-heading"><%= @course.new_record? ? "Create New Course" : "Edit Course" %></h4>
					<div class="row">
						<div class="input-field col s12">
							<%= f.text_field :code, placeholder: "Enter Course Code", autofocus: true %>
							<%= f.label :code, "Code", class: "active" %>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							<%= f.text_field :name, placeholder: "Enter Course Name" %>
							<%= f.label :name, "Course Name", class: "active" %>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							<%= f.text_area :description, rows: 12, id: "course-textarea", class: "materialize-textarea", placeholder: "Enter Full Course Description" %>
							<%= f.label :description, "Full Description", class: "active" %>
						</div>
					</div>
					<div class="row">
						<div class="col s12">
							<%= f.button class: "btn waves-effect waves-light", type: :submit do %>
								<%= @course.new_record? ? "Create" : "Update" %>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
        <div class="row cancel">
            [ <%= link_to @course.new_record? ? "CANCEL CREATE" : "CANCEL EDIT", root_path %> ]
        </div>
    </div>
</div>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<div class="row no-margin-bottom">
	<div class="col s12">
		<h3 class="left-align">Course Listing</h3>
	</div>
</div>
<div class="container">
  <div class="center">
    <%= will_paginate @courses, renderer: @custom_paginate_renderer %>
  </div>
</div>
<div class="row">
    <% @courses.each do |course| %>
      <div class="col s12 l6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title"><%= link_to course.code, course_path(course), class: "course-link" %> : <%= course.name %></span>
            <p><%= course.description %></p>
          </div>
          <div class="card-action">
            <a href="#">Enroll</a>
            <%= link_to "More Information", course_path(course) %>
            <%= link_to "Edit", edit_course_path(course) %>
          </div>
        </div>
      </div>
    <% end %>
</div>
<div class="container">
  <div class="center add-margin-bottom">
    <%= will_paginate @courses, renderer: @custom_paginate_renderer %>
  </div>
</div>

app/views/courses/new.html.erb
<% if @course.errors.any? %>
	<div class="row">
		<div class="col s12 m12 l10">
			<div class="card-panel orange error-list">
				<h5 class="card-title"><%= pluralize(@course.errors.count, "error") %> occurred while trying to create:</h5>
				<ul>
					<% @course.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
<% end %>

<div class="row new-entity">
	<div class="col s12 m12 l10">
		<div class="card-panel">
			<div class="row">
				<%= form_for(@course) do |f| %>
					<h4 class="card-title new-entity-heading">Create New Course</h4>
					<div class="row">
						<div class="input-field col s12">
							<%= f.text_field :code, placeholder: "Enter Course Code", autofocus: true %>
							<%= f.label :code, "Code" %>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							<%= f.text_field :name, placeholder: "Enter Course Name" %>
							<%= f.label :name, "Course Name" %>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							<%= f.text_area :description, rows: 12, class: "materialize-textarea", placeholder: "Enter Full Course Description" %>
							<%= f.label :description, "Full Description" %>
						</div>
					</div>
					<div class="row">
						<div class="col s12">
							<%= f.button class: "btn waves-effect waves-light", type: :submit do %>
								Create
							<% end %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/courses/show.html.erb
<div class="row new-entity">
	<div class="col s12 m12 l10">
		<div class="card blue-grey darken-1">
			<div class="card-content white-text">
				<h4 class="card-title view-heading ">Course Details</h4>
				<p class="view-label">Code: <span class="code-bold"><%= @course.code %></span></p>

                <p class="sml-pad-top"><%= @course.name %></p>
                <p class="view-label sml-pad-top">Description:</p>
                <p><%= @course.description %></p>
				<div class="row med-pad-top">
					<div class="col s12">
                        <%= link_to "Edit", edit_course_path(@course), class: "btn waves-effect waves-light" %>			
                        <%= link_to "Course List", root_path, class: "btn waves-effect waves-light" %>			
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">My University</h5>
        <p class="grey-text text-lighten-4">Your future is here and now!</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#">Get Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#">About</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2019 My University
    <a class="grey-text text-lighten-4 right" href="#">Contact Us</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <!-- Dropdown Menu Structure -->
  <ul id="dropdown1" data-turbolinks="false" class="dropdown-content">
    <li><a href="#!">Edit</a></li>
    <li><a href="#!">Permissions</a></li>
    <li class="divider"></li>
    <li><a href="#!">Payment</a></li>
  </ul>
  <ul id="dropdown2" data-turbolinks="false" class="dropdown-content">
    <li><a href="#!">Edit</a></li>
    <li><a href="#!">Permissions</a></li>
    <li class="divider"></li>
    <li><a href="#!">Payment</a></li>
  </ul>
  <ul id="dropdown-course1" data-turbolinks="false" class="dropdown-content">
    <li><%= link_to "Create Course", new_course_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Course Listing", root_path %></li>
  </ul>
  <ul id="dropdown-course2" data-turbolinks="false" class="dropdown-content">
    <li><%= link_to "Create Course", new_course_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Course Listing", root_path %></li>
  </ul>
  <ul id="dropdown-student1" data-turbolinks="false" class="dropdown-content">
    <li><%= link_to "Student Register", new_student_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Student Listing", students_path %></li>
  </ul>
  <ul id="dropdown-student2" data-turbolinks="false" class="dropdown-content">
    <li><%= link_to "Student Register", new_student_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Student Listing", students_path %></li>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper" data-turbolinks="false">
        <%= link_to "My University<i class=\"material-icons right\">school</i>".html_safe, root_path, class: "brand-logo" %>
        <a href="" data-target="mobile-menu" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a class="dropdown-trigger dropdown-head-wide" href="" data-target="dropdown-student1">Students<i class="material-icons right">arrow_drop_down</i></a></li>
          <li><a class="dropdown-trigger dropdown-head-wide" href="" data-target="dropdown-course1">Courses<i class="material-icons right">arrow_drop_down</i></a></li>
          <li><a class="dropdown-trigger dropdown-head-wide" href="" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>
  
  <ul class="sidenav" id="mobile-menu" data-turbolinks="false">
    <li class="sidenav-heading sidenav-first">Students</li>
    <li><%= link_to "Student Register", new_student_path, class: "sidenav-item" %></li>
    <li><%= link_to "Student Listing", students_path, class: "sidenav-item" %></li>
    <li class="divider"></li>
    <li class="sidenav-heading">Courses</li>
    <li><%= link_to "Create Course", new_course_path, class: "sidenav-item" %></li>
    <li><%= link_to "Course Listing", root_path, class: "sidenav-item" %></li>
    <li class="divider"></li>
    <li class="sidenav-heading">Account</li>
  </ul>

  <!-- Flash messages display here -->
  <% if flash.any? %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="row fade-out-target">
          <div class="col s12 m12 l12">
            <% if name == "success" %>
              <div class="card-panel green lighten-3">
            <% else %>
              <div class="card-panel red lighten-3">
            <% end %>
                <%= msg %>
              </div>
          </div>
        </div>
      <% end %>
  </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My University</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/students/index.html.erb
<div class="row no-margin-bottom">
  <div class="col s12">
    <h3 class="left-align">Student Directory</h3>
  </div>
</div>
<div class="container">
  <div class="center">
    <%= will_paginate @students, renderer: @custom_paginate_renderer %>
  </div>
</div>
  <div class="row">
    <% @students.each do |student| %>
      <div class="col s12 m6 l4">
        <div class="card student-card blue-grey darken-1">
          <!--
          <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/office.jpg">
          </div>
          -->
          <div class="card-content white-text">
            <span class="card-title activator"><%= student.name %><i class="material-icons right">more_vert</i></span>
            <p><%= student.email %></p>
          </div>
          <div class="card-action">
            <a href="#">EDIT</a>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">Courses Enrolled<i class="material-icons right">close</i></span>
            <p>List off the courses the student is enrolled in.</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<div class="container">
  <div class="center add-margin-bottom">
    <%= will_paginate @students, renderer: @custom_paginate_renderer %>
  </div>
</div>

app/views/students/new.html.erb
<% if @student.errors.any? %>
	<div class="row">
		<div class="col s12 m12 l10">
			<div class="card-panel orange error-list">
				<h5 class="card-title"><%= pluralize(@student.errors.count, "error") %> occurred when trying to register:</h5>
				<ul>
					<% @student.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
<% end %>

<div class="row new-entity">
	<div class="col s12 m12 l10">
		<div class="card-panel">
			<div class="row">
				<%= form_for(@student, html: { autocomplete: "off" }) do |f| %>
					<h4 class="card-title new-entity-heading">Student Registration</h4>
					<div class="row">
						<div class="input-field col s12">
							<%= f.text_field :name, placeholder: "Enter your Full Name", autocomplete: "off", autofocus: true %>
							<%= f.label :name, "Name"%>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							<%= f.email_field :email, placeholder: "Enter your Student Email Address", autocomplete: "off" %>
							<%= f.label :email, "Email" %>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							<%= f.password_field :password, placeholder: "Password", autocomplete: "new-password" %>
							<%= f.label :password, "Password" %>
						</div>
					</div>
					<div class="row">
						<div class="col s12">
							<%= f.button class: "btn waves-effect waves-light", type: :submit do %>
								Register
							<% end %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>